[package]
name = "minecraftd-manifest"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_yml = "0.0.12"
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["fs"] }
