[package]
name = "mcctl-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
log = "0.4.29"
prost = "0.14.3"
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["io-util", "net"] }

[build-dependencies]
prost-build = "0.14.3"
